set -g mouse on
set -g history-limit 100000
setw -g aggressive-resize off

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @continuum-restore 'on'
set -g @continuum-save-interval '5'
set -g @resurrect-capture-pane-contents 'on'
set -g @resurrect-processes 'ssh vim nvim less tail "~npm" "~pnpm" claude'

run '~/.tmux/plugins/tpm/tpm'
